CREATE DATABASE PET
GO

CREATE TABLE Users
(
UserID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Name VARCHAR(50) NULL,
Username VARCHAR(50) NULL UNIQUE,
Mobile VARCHAR(50) NULL,
Email VARCHAR(50) NULL UNIQUE,
Address VARCHAR(max) NULL,
PostCode VARCHAR(50) NULL,
Password VARCHAR(50) NULL,
ImageUrl VARCHAR(max) NULL,
CreateDate DATETIME NULL
)
CREATE TABLE Categories(
CategoryID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Name VARCHAR(50) NULL,
ImageURL VARCHAR(max) NULL,
IsActive BIT NULL,
CreatedDate DATETIME NULL
)
CREATE TABLE Products(
ProductID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Name VARCHAR(50) NULL,
Description VARCHAR(max) NULL,
Price DECIMAL(18,2) NULL,
Quantity INT NULL,
ImageUrl VARCHAR(max) NULL,
CategoryID INT NULL,
IsActive BIT NULL,
CreatedDate DATETIME NULL
)
CREATE TABLE Carts(
CardID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
ProductID INT NULL,
Quantity INT NULL,
UserID INT NULL,
)
CREATE TABLE Orders(
OrderDeatailsID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
OrderNo VARCHAR(max) NULL,
ProductID INT NULL,
Quatity INT NULL,
UserID INT NULL,
Status VARCHAR(50) NULL,
PaymentID INT NULL,
OrderDate DATETIME NULL,
)
CREATE TABLE Payment(
PaymentID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Name VARCHAR(50) NULL,
CardNo VARCHAR(50) NULL,
ExpiryDate VARCHAR(50) NULL,
CvvNo INT NULL,
Address VARCHAR(max) NULL,
PaymentMode VARCHAR(50) NULL,
)
CREATE TABLE Contact(
ContactID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Name VARCHAR(50) NULL,
Email VARCHAR(50) NULL,
Subject VARCHAR(200) NULL,
Message VARCHAR(max) NULL,
CreateDate DATETIME NULL,
)

